### ISSUE TITLE
Would it be possible to make it PURE dart ?

### ISSUE THREAD

**Issue by outersky** [perron2/async-zip#1]
so it can be used with Shelf to preview zip files online.
thanks!

**Comment by claudiofelber** [comment]
At the moment this is not a viable option for me. Rewriting the whole C code to Dart is quite a lot of work and I currently neither have the time nor the need to do this because the current solution does exactly what I need for an app I am currently working on (which is the reason why I wrote this package in the first place).

If you really need a pure Dart version, you're best bet might be to directly contact [Brendan Duncan](https://github.com/brendan-duncan), who is the author of the [Dart archive library](https://pub.dev/packages/archive), and ask him whether he would be willing to make his pure Dart library asynchronous (and more memory efficient).
